# Page settings
baseurl = "/"
title = "Heartland Greyhound Adoption"
languageCode = "en-us"
theme = "hugo-elate-theme"

[params]
  
  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = ""
  description = ""
  email = ""
  # Navigation
  [params.navigation]
    brand = "Heartland Greyhound Adoption"
    #home = "Home"
    work = "Adoptables"
    events = "Events"
    testimonials = "Testimonials"
    services = "Resources"
    about = "About"
    contact = "Contact"

    # You can add custom links before or after the default links
    # Assign a weight to define the order
    
    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10
  
  # Hero section
  [params.hero]
    title = "GREYT memories last a lifetime."
    subtitle = 'Finding forever homes for retired racers.'
 
  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Donate"
    description = "We rely on donations to support the entire adoption process from vetting to microchips."
    url = "#"
    button = "Support Us"
    icon = "icon-bulb"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "Volunteer"
    description = "HGA is run by volunteers. Whether it is helping at an event or fostering, we'd love your help!"
    url = "#"
    button = "Opportunities"
    icon = "icon-wrench"
    img = "img_8.jpg"

  [[params.intro.item]]
    title = "Adopt"
    description = "Interested in adoption? See what the adoption process is like and our requirements."
    url = "/adoption"
    button = "Learn Now"
    icon = "icon-rocket"
    img = "img_10.jpg"

  [params.intro.video]
    enable = false
    title = "Watch the video"
    icon = "icon-play2"
    url = "https://vimeo.com/channels/staffpicks/93951774"

  [params.intro.posts]
    enable = true
    title = "Featured Post"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
    url = "#"
    footertext = '<a class= "btn btn-primary" href="http://plmd.me/" target="_blank"><span class="btn-home">READ MORE</span></a>'


  # Work section
  [params.work]
    enable = true
    title = "Adoptables"
    description = "The number of dogs we have fluctuates. We update this list daily."
    footertext = '<a class= "btn btn-primary" href="greyhounds/" target="_self"><span class="btn-home">SEE MORE</span></a>'

    [[params.work.row]]
      img = "uploads/marty-kass-1-@1x.jpg.jpg"
      alt = "Marty Kass 1"
      title = "Marty Kass"
      subtitle = "Branding"

    [[params.work.row]]
      img = "uploads/marty-kass-2-@1x.jpg.jpg"
      alt = "Image2"
      title = "Boc's Tipn Point"
      subtitle = "Design"

    [[params.work.row]]
      img = "uploads/marty-kass-3-@1x.jpg.jpg"
      alt = "Image3"
      title = "Boc's Give Away"
      subtitle = "Design"

  # Testimonials section
  [params.testimonials]
    enable = true
    title = "Testimonials"
    description = "We take great pride in finding the perfect greyhound for you. When you adopt with HGA, you become a part of the family. <br>See what some of our family is saying."

    [[params.testimonials.item]]
      quote = "&ldquo;We wouldn't have met the two most amazing Greyhounds in the world, Flynn & Maggie, without Heartland Greyhound Adoption. They are a wonderful organization that puts the best interest of the dogs ahead of anything else. We are grateful for all their hard work and dedication to the breed.&rdquo;"
      person = 'Sarah Ryan'
      img = "person1.jpg"
      alt = "Person1"

    [[params.testimonials.item]]
      quote = "&ldquo;There are many wonderful greyhound adoption groups, but for me, Heartland stands just a little bit taller mainly because of all the good foster work they do to make sure that whenever a hound is placed permanently with a family, that dog will likely have found their &ldquo;forever&rdquo; home. Kudos!&rdquo;"
      person = 'Barb Biffle Bennett'
      img = "person2.jpg"
      alt = "Person2"

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. &rdquo;"
      person = 'Liz Cleaveland'
      img = "person3.jpg"
      alt = "Person3"
    
  # Events section
  [params.events]
    enable = true
    title = "Events"
    description = "Whether you've never met a greyhound or have five in your family, there is an event for you! See what is coming up soon."
    footertext = '<a class= "btn btn-primary" href="http://plmd.me/" target="_blank"><span class="btn-home">SEE MORE</span></a>'



  # Services section
  [params.services]
    enable = true
    title = "Resources"
    description = "Whether you're new to greyhounds or have been around them all your life, we are here to help."

    [[params.services.item]]
      title = "Frequently Asked Questions"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "icon-support"

    [[params.services.item]]
      title = "Discussion"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "icon-bubbles"
    [[params.services.item]]
      title = "Blog"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "icon-home"

      [[params.services.item]]
      title = "Greyhound Data"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"      
      icon = "icon-monitor"

  # About section
  [params.about]
    enable = true
    title = "About"
    description = "Heartland Greyhound Adoption is a volunteer not-for-profit 501&#40;c&#41;(3) organization, formed and operating in central Iowa to promote the adoption of retired racing greyhounds."
    footertext = '<a class= "btn btn-primary" href="http://plmd.me/" target="_blank"><span class="btn-home">READ MORE</span></a>'

    [[params.about.item]]
      name = "Jody Phelps"
      position = "President"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person1.jpg"
      alt = "Jody Phelps"
      social = [
        ["icon-envelope", "mailto:president@hga.dog"],
      ]

    [[params.about.item]]
      name = "Rob Smith"
      position = "Vice President"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person2.jpg"
      alt = "Person2"
      social = [
        ["icon-envelope", "#"]
      ]

    [[params.about.item]]
      name = "Lisa Helmick"
      position = "Secretary"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person3.jpg"
      alt = "Person3"
      social = [
        ["icon-envelope", "#"]
      ]

    [[params.about.item]]
      name = "Larry Ben"
      position = "Treasurer"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person3.jpg"
      alt = "Person3"
      social = [
        ["icon-envelope", "#"]
      ]

    [[params.about.item]]
      name = "Gretchen Meyer"
      position = "Member-at-Large"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person3.jpg"
      alt = "Person3"
      social = [
        ["icon-envelope", "#"]
      ]

  # Counters section
  [params.counters]
    enable = true
    title = "Stats"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "Finished projects"
      icon = "icon-people"
      from = 0
      to = 89
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Lines of code"
      icon = "icon-code"
      from = 0
      to = 2343409
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Cups of coffee"
      icon = "icon-cup"
      from = 0
      to = 1302
      interval = 50
      speed = 5000

  # Contact section
  [params.contact]
    enable = true
    map = false
    title = "Get in touch"
    description = "Do you have questions or comments? It's easy to get in touch with HGA."
    
    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "P.O. Box 342, Bondurant, IA, 50035"],
        ["icon-phone", "(515) 210-0459"],
        ["icon-envelope", "info@hga.dog"],
       # ["icon-globe", '<a href="http://freehtml5.co/" target="_blank">freehtml5.co</a>']
      ]

    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Send message"

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; Heartlang Greyhound Adoption. All Rights Reserved. <br>Created by Houston Perrett'


  # Application section
  [params.application]
    name = "Name"
    occupation = "Occupation"
    address = "Address"
    city = "City"
    state = "State"
    zip = "Zip Code"
    email = "Email"
    phone = "Phone"
    employer = "Employer(s)"
    age = "Age"
    message = "Message"
    button = "Send message"