# Page settings
baseurl = "/"
title = "Heartland Greyhound Adoption"
languageCode = "en-us"
theme = "hugo-elate-theme"

[params]
  
  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = ""
  description = ""
  email = ""
  # Navigation
  [params.navigation]
    brand = "Heartland Greyhound Adoption"
    #home = "Home"
    work = "Adoptables"
    events = "Events"
    testimonials = "Testimonials"
    services = "Resources"
    about = "About"
    contact = "Contact"

    # You can add custom links before or after the default links
    # Assign a weight to define the order
    
    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10
  
  # Hero section
  [params.hero]
    title = "GREYT memories last a lifetime."
    subtitle = 'Finding forever homes for retired racers.'
 
  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Donate"
    description = "We rely on donations to support the entire adoption process from vetting to microchips."
    url = "#"
    button = "Support Us"
    icon = "icon-bulb"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "Volunteer"
    description = "HGA is run by volunteers. Whether it is helping at an event or fostering, we'd love your help!"
    url = "#"
    button = "Opportunities"
    icon = "icon-wrench"
    img = "img_8.jpg"

  [[params.intro.item]]
    title = "Adopt"
    description = "Interested in adoption? See what the adoption process is like and our requirements."
    url = "/adoption"
    button = "Learn How"
    icon = "icon-rocket"
    img = "img_10.jpg"

  [params.intro.video]
    enable = false
    title = "Watch the video"
    icon = "icon-play2"
    url = "https://vimeo.com/channels/staffpicks/93951774"

  [params.intro.posts]
    enable = true
    title = "Featured Post"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
    url = "#"
    footertext = '<a class= "btn btn-primary" href="blog/" target="_blank"><span class="btn-home">READ MORE</span></a>'


  # Work section
  [params.work]
    enable = true
    title = "Adoptables"
    description = "The number of dogs we have fluctuates. We update this list daily."
    footertext = '<a class= "btn btn-primary" href="greyhounds/" target="_self"><span class="btn-home">SEE MORE</span></a>'

    [[params.work.row]]
      img = "uploads/marty-kass-1-@1x.jpg.jpg"
      alt = "Marty Kass 1"
      title = "Marty Kass"
      subtitle = "Branding"

    [[params.work.row]]
      img = "uploads/marty-kass-2-@1x.jpg.jpg"
      alt = "Image2"
      title = "Boc's Tipn Point"
      subtitle = "Design"

    [[params.work.row]]
      img = "uploads/marty-kass-3-@1x.jpg.jpg"
      alt = "Image3"
      title = "Boc's Give Away"
      subtitle = "Design"

  # Testimonials section
  [params.testimonials]
    enable = true
    title = "Testimonials"
    description = "We take great pride in finding the perfect greyhound for you. When you adopt with HGA, you become a part of the family. <br>See what some of our family is saying."

    [[params.testimonials.item]]
      quote = "&ldquo;We wouldn't have met the two most amazing Greyhounds in the world, Flynn & Maggie, without Heartland Greyhound Adoption. They are a wonderful organization that puts the best interest of the dogs ahead of anything else. We are grateful for all their hard work and dedication to the breed.&rdquo;"
      person = 'Sarah Ryan'
      img = "person1.jpg"
      alt = "Person1"

    [[params.testimonials.item]]
      quote = "&ldquo;There are many wonderful greyhound adoption groups, but for me, Heartland stands just a little bit taller mainly because of all the good foster work they do to make sure that whenever a hound is placed permanently with a family, that dog will likely have found their &ldquo;forever&rdquo; home. Kudos!&rdquo;"
      person = 'Barb Biffle Bennett'
      img = "person2.jpg"
      alt = "Person2"

    [[params.testimonials.item]]
      quote = "&ldquo;HGA genuinely cares about every dog that comes to them. Since we've adopted our greyhound, HGA has been a second family to us.&rdquo;"
      person = 'Liz Cleaveland'
      img = "person3.jpg"
      alt = "Person3"
    
  # Events section
  [params.events]
    enable = true
    title = "Events"
    description = "Whether you've never met a greyhound or have five in your family, there is an event for you! See what is coming up soon."
    footertext = '<a class="btn btn-primary" href="events/" target="_self"><span class="btn-home">SEE MORE</span></a>'



  # Services section
  [params.services]
    enable = true
    title = "Resources"
    description = "Whether you're new to greyhounds or have been around them all your life, we are here to help."

    [[params.services.item]]
      title = "Adoption Essentials"
      description = "It's important to have things in order before adopting a greyhound. The essentials are what we believe to be vital to your success as a new member of the cult including supplies to have, finding a vet, and bringing home your new family member."
      icon = "icon-support"
      link = "essentials"

    [[params.services.item]]
      title = "Frequently Asked Questions"
      description = "Greyhounds are a unique breed. They have their special quirks and needs that aren't like other dogs. Here are some of the most frequent questions we receive from potential adopters to help you."
      icon = "icon-bubbles"
      link = "faq"

  # About section
  [params.about]
    enable = true
    title = "About"
    description = "Heartland Greyhound Adoption is a volunteer not-for-profit 501&#40;c&#41;(3) organization, formed and operating in central Iowa to promote the adoption of retired racing greyhounds."
    footertext = '<a class= "btn btn-primary" href="about/" target="_blank"><span class="btn-home">READ MORE</span></a>'

    [[params.about.item]]
      name = "Jody Phelps"
      position = "President"
      description = ""
      img = "person1.jpg"
      alt = "Jody Phelps"
 

    [[params.about.item]]
      name = "Lori Murga"
      position = "Vice President"
      description = ""
      img = "person2.jpg"
      alt = "Person2"
     

    [[params.about.item]]
      name = "Lisa Helmick"
      position = "Secretary"
      description = ""
      img = "person3.jpg"
      alt = "Person3"
     

    [[params.about.item]]
      name = "Ryan Hasty"
      position = "Treasurer"
      description = ""
      img = "person3.jpg"
      alt = "Person3"
      

    [[params.about.item]]
      name = "Gretchen Meyer"
      position = "Member-at-Large"
      description = ""
      img = "person3.jpg"
      alt = "Person3"
      

    [[params.about.item]]
      name = "Joe Shearer"
      position = "Member-at-Large"
      description = ""
      img = "person3.jpg"
      alt = "Person3"
      

    [[params.about.item]]
      name = "Vacant"
      position = "Member-at-Large"
      description = ""
      img = "person3.jpg"
      alt = "Person3"
      

  # Counters section
  [params.counters]
    enable = true
    title = "Stats"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "Board Members"
      icon = "icon-people"
      from = 0
      to = 7
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Volunteers"
      icon = "icon-people"
      from = 0
      to = 15
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Members"
      icon = "icon-people"
      from = 0
      to = 236
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Happy Tails"
      icon = "icon-people"
      from = 0
      to = 776
      interval = 50
      speed = 5000

  # Contact section
  [params.contact]
    enable = true
    map = false
    title = "Get in touch"
    description = "Do you have questions or comments? It's easy to get in touch with HGA."
    
    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "P.O. Box 342, Bondurant, IA, 50035"],
        ["icon-phone", "(515) 210-0459"],
        ["icon-envelope", "support@hga.dog"],
       # ["icon-globe", '<a href="http://freehtml5.co/" target="_blank">freehtml5.co</a>']
      ]

    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Send message"

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; Heartland Greyhound Adoption. All Rights Reserved. <br>Created by Houston Perrett'


  # Application section
  [params.application]
    name = "Name"
    occupation = "Occupation"
    address = "Address"
    city = "City"
    state = "State"
    zip = "Zip Code"
    email = "Email"
    phone = "Phone"
    employer = "Employer(s)"
    age = "Age"
    message = "Message"
    button = "Send message"